# Generated by Django 5.0 on 2024-01-22 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_alter_singup_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Description', models.CharField(max_length=1200)),
                ('Date', models.DateField()),
                ('Users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.singup')),
            ],
        ),
    ]
