# Generated by Django 5.0 on 2024-01-22 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_userprofile'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userprofile'),
        ),
    ]
